#!/bin/bash

NAME="armgraph"
VERSION="0.1.3"

FILE_NAME_WITHOUT_VERSION=$NAME".js"
FILE_NAME_MIN=$NAME".min"-$VERSION".js"

PATH_TO_COMPILER="./lib/Closure-compiler/compiler.jar"

COMPILATION_LEVEL="WHITESPACE_ONLY"
# COMPILATION_LEVEL="SIMPLE_OPTIMIZATIONS"
# COMPILATION_LEVEL="ADVANCED_OPTIMIZATIONS"

python ./lib/generateCompresedFile.py ./modules "$PATH_TO_COMPILER" "$COMPILATION_LEVEL" "$FILE_NAME_WITHOUT_VERSION"

echo "$FILE_NAME_WITHOUT_VERSION"

echo "$FILE_NAME_MIN"
cp "$FILE_NAME_WITHOUT_VERSION" "$FILE_NAME_MIN"